<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head><meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<title>libtcod documentation | ${TITLE}</title>
<script type="text/javascript" src="${SCRIPT}"></script>
<link href="${STYLESHEET}" rel="stylesheet" type="text/css"></head>
<link type="text/css" rel="stylesheet" href="../css/shCore.css"></link>
<link type="text/css" rel="stylesheet" href="../css/shThemeDefault.css"></link>
<script language="javascript" src="../js/shCore.js"></script>
<script language="javascript" src="../js/shBrushBash.js"></script>
<body><div class="header">
<p><span class="title1">libtcod</span><span class="title2">documentation</span></p>
</div>
<div class="breadcrumb"><div class="breadcrumbtext"><p>
you are here: ${LOCATION}<br>
${PREV_LINK} ${NEXT_LINK}
</p></div></div>
<div class="filter">${FILTER_FORM}</div>
<div class="main"><div class="maintext">
<h1>${PAGE_TITLE}</h1>
${PAGE_CONTENT}
</div></div>
<div class="footer"><div class="footertext">
	<p>libtcod 1.5.2, &copy; 2008, 2009, 2010, 2012 Jice & Mingos<br>
	This file has been generated by doctcod.</p>
	<p><table width='100%'><tr><td><a href="http://doryen.eptalys.net/libtcod">libtcod website</a></td>
	<td><a href="http://doryen.eptalys.net/forum/index.php?board=12.0">libtcod on Roguecentral forums</a></td>
	<td><a href="http://doryen.eptalys.net/libtcod/tutorial">libtcod tutorials</a></td>
  </tr></table></p>
</div></div>
</body>
<script>
initFilter();
SyntaxHighlighter.all();
</script>
</html>
