<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head><meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<title>libtcod documentation | ${TITLE}</title>
<script type="text/javascript" src="${SCRIPT}"></script>
<link href="${STYLESHEET}" rel="stylesheet" type="text/css"></head>
<body><div class="header">
<p><span class="title1">libtcod</span><span class="title2">documentation</span></p>
</div>
<div class="breadcrumb"><div class="breadcrumbtext"><p>
you are here: ${LOCATION}<br>
${PREV_LINK} ${NEXT_LINK}
</p></div></div>
<div class="filter">${FILTER_FORM}</div>
<div class="main"><div class="maintext">
<h1>${PAGE_TITLE}</h1>
${PAGE_CONTENT}
</div></div>
<div class="footer"><div class="footertext">
	<p>libtcod 1.5.1, &copy; 2008, 2009, 2010, 2012 Jice & Mingos<br>
	This file has been generated by doctcod.</p>
	<p><table width='100%'><tr><td><a href="http://doryen.eptalys.net/libtcod">libtcod website</a></td>
	<td><a href="http://doryen.eptalys.net/forum/index.php?board=12.0">libtcod on Roguecentral forums</a></td>
  <td><a href="http://www.youtube.com/watch?v=PY9lJnVQbXs&feature=PlayList&p=553E3D00A1460331&playnext_from=PL&index=0&playnext=1">libtcod HOWTO video tutorials</a></td></tr></table></p>
</div></div>
</body>
<script>
initFilter();
</script>
</html>
